### ISSUE TITLE
No error but no icon

### ISSUE THREAD

**Issue by vandiel01** [Caerdon/CaerdonWardrobe#28]
Bag is fine, the GBank no longer show icons if known or not.  Only shows BoE on bottom.

**Comment by Caerdon** [comment]
I'm seeing icons show up on the guild bank.  Any other details or add-ons involved?  You might confirm the options in the Guild Bank settings for Caerdon Wardrobe and check / uncheck the options to try and force an update.

**Comment by vandiel01** [comment]
It only shows "W", it does not show 'loot bag' or X or 'checkmark' for any gears.

gbank:
![image](https://user-images.githubusercontent.com/52209920/200196831-3ba1f395-1861-419c-bffa-b3236aa016bb.png)
bag:
![image](https://user-images.githubusercontent.com/52209920/200197316-427515e1-ac39-4ef5-aa02-40089e058186.png)
settings: everything is check marked except for Debug, only ATT and Caedron was running when I was working on this

**Comment by vandiel01** [comment]
It's possible that it's also "Can I Mog It?" related too, I've posted an bug report there as well.

**Comment by Caerdon** [comment]
I don't show a checkmark, so that's probably tied to Can I Mog It, but anything Can I Mog It identifies as learnable should be identified as learnable by Caerdon Wardrobe if you have the options all enabled (otherwise, it's a bug I need to fix).

I've confirmed I'm seeing all the expected icons, so I'm guessing there are a few you don't have enabled right now (or something went wrong with the settings upgrade).

If you want to see all possible learnable things, go to the Caerdon Wardrobe addon settings, and make sure to check "Include different items w/ the same look (you completionist, you)" and possibly the "Including identical items w/ lower levels" in the "General" section and then make sure everything is checked in the "Guild Bank" section.

**Comment by Caerdon** [comment]
Closing for now... if you're still having issues here with Caerdon Wardrobe, please let me know!
